services:
  
  db:
    image: postgres:latest
    container_name: "social_db"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: social
    ports:
      - "5432:5432"
    volumes:
      - ./cmd/database:/docker-entrypoint-initdb.d
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d social"]
      interval: 5s
      timeout: 5s
      retries: 5

  socialapp:
    build: .
    container_name: "social_app"
    ports:
     - "8008:8008"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=social
    depends_on:
      - db 
      
volumes:
  db_data: